### ISSUE TITLE
Can't build on Windows.

### ISSUE THREAD

**Issue by tomByrer** [PeculiarVentures/node-webcrypto-ossl#150]
Win 10
Node 12.4.0
I was able to [install node-gyp ](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#prerequisites)& build bson with it.

But I still get this error:
```bash
npm ERR! node-webcrypto-ossl@1.0.39 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-webcrypto-ossl@1.0.39 install script.
```

Any tips?  Is there an alternative, or is OSSL really needed for local testing?

**Comment by rmhrisk** [comment]
This package is dependent on OSSL.

see https://github.com/PeculiarVentures/webcrypto for one that uses only node crypto and has the associated limitations.

**Comment by tomByrer** [comment]
TY!
Do the two have similar APIs; eg are easily swapped?

**Comment by rmhrisk** [comment]
Both are API compatible with webcrypto, thi OSSL based one supports more algorithms and modes.

It will compile on windows but debuting environmental build issues with dependencies as is needed with Native modules can be a hassle so we created the other one.

**Comment by microshine** [comment]
@tomByrer I've fixed Windows error and published `+ node-webcrypto-ossl@1.0.48`

**Comment by tomByrer** [comment]
I was able to build & seems to work; cheers!

**Comment by jenishngl** [comment]
I still have this issue when i do `npm install node-webcrypto-ossl` in Windows 10
